### ISSUE TITLE
Build error dom7@2.1.2 build-prod: `cross-env NODE_ENV=production gulp build`

### ISSUE THREAD

**Issue by tvalentina** [nolimits4web/Dom7#20]
Hi @nolimits4web please, can you help me to compile the dom7 framework? When I running the cml **npm -verbose run build-prod** I receive the following error:
```
npm info it worked if it ends with ok
npm verb cli [ '/usr/local/bin/node',
npm verb cli   '/usr/local/bin/npm',
npm verb cli   '-verbose',
npm verb cli   'run',
npm verb cli   'build-prod' ]
npm info using npm@6.5.0
npm info using node@v11.4.0
npm verb run-script [ 'prebuild-prod', 'build-prod', 'postbuild-prod' ]
npm info lifecycle dom7@2.1.2~prebuild-prod: dom7@2.1.2
npm info lifecycle dom7@2.1.2~build-prod: dom7@2.1.2

> dom7@2.1.2 build-prod /Volumes/development/openlibs/dom7
> cross-env NODE_ENV=production gulp build

gulp[2197]: ../src/node_contextify.cc:628:static void node::contextify::ContextifyScript::New(const FunctionCallbackInfo<v8::Value> &): Assertion `args[1]->IsString()' failed.
 1: 0x10006302f node::Abort() [/usr/local/bin/node]
 2: 0x100062f61 node::PrintErrorString(char const*, ...) [/usr/local/bin/node]
 3: 0x10006093d node::contextify::ContextifyScript::New(v8::FunctionCallbackInfo<v8::Value> const&) [/usr/local/bin/node]
 4: 0x100221f37 v8::internal::FunctionCallbackArguments::Call(v8::internal::CallHandlerInfo*) [/usr/local/bin/node]
 5: 0x1002211f8 v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<true>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::FunctionTemplateInfo>, v8::internal::Handle<v8::internal::Object>, v8::internal::BuiltinArguments) [/usr/local/bin/node]
 6: 0x100220bd7 v8::internal::Builtin_Impl_HandleApiCall(v8::internal::BuiltinArguments, v8::internal::Isolate*) [/usr/local/bin/node]
 7: 0x2bbe3444fb7d
 8: 0x2bbe34409e66
 9: 0x2bbe3448a400
npm verb lifecycle dom7@2.1.2~build-prod: unsafe-perm in lifecycle true
npm verb lifecycle dom7@2.1.2~build-prod: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Volumes/development/openlibs/dom7/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin
npm verb lifecycle dom7@2.1.2~build-prod: CWD: /Volumes/development/openlibs/dom7
npm info lifecycle dom7@2.1.2~build-prod: Failed to exec build-prod script
npm verb stack Error: dom7@2.1.2 build-prod: `cross-env NODE_ENV=production gulp build`
npm verb stack Exit status 1
npm verb stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
npm verb stack     at EventEmitter.emit (events.js:189:13)
npm verb stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
npm verb stack     at ChildProcess.emit (events.js:189:13)
npm verb stack     at maybeClose (internal/child_process.js:978:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
npm verb pkgid dom7@2.1.2
npm verb cwd /Volumes/development/openlibs/dom7
npm verb Darwin 17.7.0
npm verb argv "/usr/local/bin/node" "/usr/local/bin/npm" "-verbose" "run" "build-prod"
npm verb node v11.4.0
npm verb npm  v6.5.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! dom7@2.1.2 build-prod: `cross-env NODE_ENV=production gulp build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the dom7@2.1.2 build-prod script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm verb exit [ 1, true ]
npm timing npm Completed in 564ms
```
Thank you in advance.
Valentina

**Comment by tvalentina** [comment]
**Resolved.**

The incompatibility between gulp.js and node.js versions cause the error.
After I downgrading node.js to the 9.11.2 version, the build working fine.

Just a suggest, indicate the main components version in the documentation can help to reduce the errors. :)

Thanks and Happy Christmas,
V
